_BASE_: "../base-finetune.yaml"
RUN_N_TIMES: 1
DATA:
  NAME: "nabirds"
  DATAPATH: ""  #TODO: need to specify here
  NUMBER_CLASSES: 555
  MULTILABEL: False
MODEL:
  TYPE: "vit"
SOLVER:
  BASE_LR: 0.00375
  WEIGHT_DECAY: 0.01
