_BASE_: "../../../base-prompt.yaml"
RUN_N_TIMES: 1
DATA:
  NAME: vtab-dsprites(predicted_attribute="label_x_position",num_classes=16)
  DATAPATH: "/shared/kgcoe-research/spl/VTAB-1k/Structured/"  #TODO: need to specify here
  NUMBER_CLASSES: 16
  MULTILABEL: False
MODEL:
  TYPE: "vit"
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.001
