_BASE_: "../../base-prompt_changed_P_VK.yaml"
RUN_N_TIMES: 1
DATA:
  NAME: "imagenet1k"
  DATAPATH: "shared/kgcoe-research/spl/imagenet1k/"  #TODO: need to specify here
  NUMBER_CLASSES: 1000
  MULTILABEL: False
MODEL:
  TYPE: "vit"
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.001
