NUM_GPUS: 1
NUM_SHARDS: 1
OUTPUT_DIR: ""
RUN_N_TIMES: 1
MODEL:
  TRANSFER_TYPE: "end2end"
  TYPE: "swin"
  LINEAR:
    MLP_SIZES: []
SOLVER:
  SCHEDULER: "cosine"
  WARMUP_EPOCH: 5
  LOSS: "softmax"
  OPTIMIZER: "adamw"
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0001
  LOG_EVERY_N: 100
  TOTAL_EPOCH: 100
  PATIENCE: 300
DATA:
  NAME: ""
  NUMBER_CLASSES: -1
  DATAPATH: ""
  FEATURE: "swinb_imagenet22k_224"
  BATCH_SIZE: 224 # original batch size is 384
  NUM_WORKERS: 8