NUM_GPUS: 1
NUM_SHARDS: 1
OUTPUT_DIR: "output"
RUN_N_TIMES: 1
MODEL:
  TRANSFER_TYPE: "prompt"
  TYPE: "vit"
  LINEAR:
    MLP_SIZES: []
SOLVER:
  SCHEDULER: "cosine"
  PATIENCE: 300
  LOSS: "softmax"
  OPTIMIZER: "sgd"
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0001
  LOG_EVERY_N: 5
  WARMUP_EPOCH: 3
  TOTAL_EPOCH: 5
DATA:
  NAME: "test"
  NUMBER_CLASSES: -1
  DATAPATH: ""
  FEATURE: "sup_vitb16_224"
  BATCH_SIZE: 64
