_BASE_: "../base-linear.yaml"
RUN_N_TIMES: 1
DATA:
  NAME: "StanfordDogs"
  DATAPATH: ""  #TODO: need to specify here
  NUMBER_CLASSES: 120
  MULTILABEL: False
MODEL:
  TYPE: "vit"
SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0001